// -----------------------------------------------------------------------------
// HELP_CONTENT — verbatim Usage Guide content, embedded as a compile-time
// constant for the cdn_help tool.
//
// Source: https://www.notion.so/356de14e04cc8149869df1c888499483
// (CDN w MCP — Usage Guide)
//
// Why a constant and not a runtime fetch:
//   - Worker bundles their imports at build time; no Notion credentials need
//     to live in the Worker, no Notion API call on every help-tool call.
//   - Decouples the Worker from Notion availability.
//   - Faster: the help response is always synchronous from RAM.
//
// Editing rules (head-session policy):
//   - The Notion page is the SOURCE OF TRUTH. Whenever the guide is updated
//     there, this constant should be regenerated by the head session in a
//     subsequent phase (or hotfix), then the Worker redeployed.
//   - Mechanical transforms applied when extracting from Notion (Phase 5.0a):
//       * Drop the page-level callout block at the top (the one that talks
//         about the cdn_help tool itself — embedding it would read recursively).
//       * Synthesize the H1 + a one-line intro from the callout's first line.
//       * Convert Notion's HTML <table>...</table> blocks to standard markdown
//         pipe tables.
//       * Unescape Notion-export backslash escapes on `<`, `>`, and `~`.
//
// Keep this file pure data. The cdn_help handler imports HELP_CONTENT and
// returns it inside the standard MCP `content[0].text` envelope.
//
// Per Build Plan rule 3 corollary (factor smaller, not flag-add): the help
// content is its own module, not inlined in the tool handler. If a future
// phase adds topic-scoped responses, the topic→slice logic lives in this
// module too — the handler stays a thin adapter.
// -----------------------------------------------------------------------------

export const HELP_CONTENT = `# CDN w MCP — Usage Guide

What this CDN does, how it's organized, and how to use it from inside Claude.

# What this is

A personal CDN backed by Cloudflare R2 (bytes), Cloudflare D1 (metadata), and a Cloudflare Worker that exposes everything as an MCP server. Upload images, videos, HTML files, or any other assets, organized into **projects** (folders), and manage them entirely from inside Claude (or any MCP client) via natural-language tool calls.

Everything you upload gets a **stable public URL** at \`https://cdn.22d.app/<project>/<filename>\`. URLs don't change when you replace an asset. That's the core promise.

# Core concepts

## Projects

Logical folders. Auto-created on first upload — you don't have to pre-create them. Use them to organize content:

- \`blog\` for blog images
- \`irondad\` for workout videos
- \`proposals\` for client deliverables
- whatever names make sense for your work

A project that exists in D1 but has no files is harmless — it just shows up in \`cdn_list_projects\` with \`file_count: 0\`. There's no \`cdn_delete_project\` tool currently; empty projects accumulate but don't cost anything.

## Files

Bytes uploaded to a project. Each file is identified by its \`(project, name)\` pair. The \`name\` can include slashes for sub-paths (e.g. \`q2/report.pdf\` inside the \`client-deliverables\` project produces the URL \`https://cdn.22d.app/client-deliverables/q2/report.pdf\`).

## Public URLs

Format: \`https://cdn.22d.app/<project>/<filename>\`.

- Anonymous — anyone with the URL can fetch. There's no auth on reads.
- Cached at Cloudflare's edge for 60 seconds (\`Cache-Control: public, max-age=60\`). After a replace, fresh bytes propagate globally within ~60s.
- Append a cache-buster query for instant verification: \`?v=2\` or \`?bust=<timestamp>\`.

## Version + last_replaced_at

Each file has a \`version\` (starts at 1 on first upload, increments by 1 on each replace) and a \`last_replaced_at\` (null until first replace, then ISO timestamp). Useful for detecting changes programmatically.

## Content-Type

MIME type recorded in D1 and served as the \`Content-Type\` header. Inferred automatically from the filename extension if you don't pass \`content_type\` explicitly. Known extensions include: png, jpg, jpeg, gif, webp, svg, mp4, webm, mp3, html, css, js, json, txt, pdf. Unknown extensions fall back to \`application/octet-stream\`.

# Common workflows

## Upload a blog image

Use the **cdn-file-upload skill** (from cdn-mcp-plugin). It probes the sandbox's network egress and either uploads directly or hands the user a clickable script — see *Uploading from inside a Cowork session* below. Bytes never travel through the MCP as base64; \`cdn_upload_file\` hard-rejects external callers as of Phase 11.3.

Under the hood, the byte-moving sequence is always the same:

\`\`\`javascript
cdn_signed_upload_url({ project: "blog", name: "post-2026-05-04-hero.png", content_type: "image/png" })
// → PUT the bytes to upload_url with EVERY header from required_headers
cdn_finalize_upload({ project: "blog", name: "post-2026-05-04-hero.png", content_type: "image/png", size_bytes: 412334 })
\`\`\`

- Auto-creates the \`blog\` project if it doesn't exist.
- \`cdn_signed_upload_url\` errors with \`file_exists\` if the file already exists at \`(blog, post-2026-05-04-hero.png)\`. Pass \`replace: true\` to overwrite, OR use \`cdn_replace_file\` (cleaner intent).
- \`cdn_finalize_upload\` returns \`{ url, project, name, size_bytes, content_type, uploaded_at, version: 1, ... }\`.
- Public URL: \`https://cdn.22d.app/blog/post-2026-05-04-hero.png\` — deterministic, known before the upload starts.

## Replace an image without breaking embedded links

\`\`\`javascript
cdn_replace_file({
  project: "blog",
  name: "post-2026-05-04-hero.png",
  content_base64: "<new-base64-bytes>"
})
\`\`\`

- Errors with \`file_not_found\` if the file doesn't exist — create it first via the upload path above (\`cdn_signed_upload_url\` → PUT → \`cdn_finalize_upload\`), then replace.
- Same R2 key, same public URL. Bumps \`version\` to 2 (then 3, 4, ...). Sets \`last_replaced_at\` to now.
- New bytes serve at the public URL within ~60s (edge cache TTL). For instant verification, fetch with \`?v=2\` or \`?bust=<timestamp>\`.

## Upload a video larger than 100MB

The Worker has a request-body limit of ~100MB. For large videos, use the two-step signed-URL flow that PUTs bytes directly to R2:

\`\`\`javascript
// Step 1: get a presigned PUT URL
const { upload_url, required_headers } = cdn_signed_upload_url({
  project: "videos",
  name: "demo-2026-05-04.mp4",
  content_type: "video/mp4",
  expires_in_seconds: 900  // optional, default 15 min, max 60 min
})

// Step 2: PUT bytes directly to R2 from your client.
// MUST include all headers from required_headers, exactly as returned.
// From terminal:
//   curl -X PUT \\
//     -H "Content-Type: video/mp4" \\
//     -H "Cache-Control: public, max-age=60" \\
//     --data-binary @demo.mp4 \\
//     "$upload_url"

// Step 3: tell the CDN to record metadata
cdn_finalize_upload({
  project: "videos",
  name: "demo-2026-05-04.mp4",
  content_type: "video/mp4",
  size_bytes: 152428800  // exact byte count of the file
})
\`\`\`

- The presigned URL expires after \`expires_in_seconds\`. Default 15 min.
- \`size_bytes\` in \`cdn_finalize_upload\` must match the actual R2 object's size — the Worker verifies via \`head()\` and rejects mismatches as \`size_mismatch\`. Catches partial uploads.
- If you skip step 3, bytes sit in R2 untracked by D1. They still serve at the public URL but won't appear in \`cdn_list_files\`. You can call \`cdn_finalize_upload\` later to recover.

## See what's there

\`\`\`javascript
cdn_list_projects()                                  // all projects, with file_count + total_size_bytes
cdn_list_files({ project: "blog" })                  // all files in one project
cdn_list_files()                                     // all files across all projects
cdn_list_files({ project: "blog", limit: 50, cursor: "..." })  // paginated
cdn_get_file({ project: "blog", name: "..." })       // single file metadata
cdn_get_stats()                                      // global: project_count, file_count, total_size_bytes, per-project breakdown
cdn_get_stats({ project: "blog" })                   // single project's totals
\`\`\`

## Clean up

\`\`\`javascript
cdn_delete_file({ project: "blog", name: "..." })
\`\`\`

- Removes from R2 (bytes) and D1 (metadata row).
- Idempotent on the R2 side: deleting an already-missing object doesn't error.
- Errors with \`file_not_found\` if the D1 row doesn't exist.
- Doesn't auto-delete the project row when it becomes empty. Empty projects stay in \`cdn_list_projects\` with \`file_count: 0\`.

## Pre-create an empty project

\`\`\`javascript
cdn_create_project({ name: "newproject", description: "Optional description" })
\`\`\`

Optional — projects auto-create on first upload. Use this if you want the project to exist as scaffolding before any files arrive (useful for tooling that lists projects upfront).

# Uploading from inside a Cowork session (sandbox limitations)

Cowork sessions run in a network-restricted sandbox whose egress allowlist is **per-session** — it only applies to sessions started AFTER the user changed the setting. So reachability varies session to session and **must be probed, never assumed**:

\`\`\`bash
curl -sI --max-time 10 https://cdn.22d.app/
\`\`\`

A real origin response (\`server: cloudflare\`) means egress works. A timeout, or \`X-Proxy-Error: blocked-by-allowlist\`, means it doesn't.

Two hosts matter, and they are allowlisted separately:

- \`cdn.22d.app\` — the public CDN (the probe + verify target)
- \`<account>.r2.cloudflarestorage.com\` — the S3 endpoint presigned PUTs actually target

Having the first without the second is a real, observed configuration: the probe passes but the byte transfer is refused. **File size does not select the pattern — reachability does.** There is no base64 path: \`cdn_upload_file\` hard-rejects external callers as of Phase 11.3.

## Pattern A — the cdn-file-upload skill (the default; just use this)

Install cdn-mcp-plugin and let the skill do it. It probes egress, sanitizes the filename, picks Pattern B or C for you, verifies the public URL, and hands back the link. Everything below is what the skill is doing internally — you rarely need to run it by hand.

## Pattern B — zero-click: signed URL + PUT + finalize (sandbox HAS egress)

\`\`\`bash
# 1. Mint a presigned PUT (15 min default)
#    cdn_signed_upload_url({ project, name, content_type })
#    → upload_url + required_headers

# 2. PUT the bytes straight from the sandbox
curl -sS --max-time 60 -X PUT -T ./hero.png \\
  -H "Content-Type: image/png" \\
  -H "Cache-Control: public, max-age=60" \\
  "$UPLOAD_URL"
# Send EVERY header from required_headers, byte-identical. Both Content-Type
# and Cache-Control are signed — omit either and R2 returns 403
# SignatureDoesNotMatch, even with open egress.

# 3. Commit the metadata
#    cdn_finalize_upload({ project, name, content_type, size_bytes })
\`\`\`

Works for any size (curl streams from disk; no payload cap). Requires BOTH hosts allowlisted, and the source file must be readable from the sandbox. If the PUT is refused, fall back to Pattern C — an abandoned presign is harmless, since no D1 row exists until finalize.

## Pattern C — local terminal / CLI (sandbox has NO egress)

Run the upload on the user's host, where the network is unrestricted. The \`cdn\` CLI wraps the same three steps (it PUTs to R2 with its own credentials, then calls \`cdn_finalize_upload\`):

\`\`\`bash
cdn upload blog ./hero.png --name hero.png
\`\`\`

The skill's fallback is a double-clickable \`.command\`/\`.sh\`/\`.bat\` wrapper around exactly this. The same manual \`curl -X PUT\` from Pattern B also works from a real terminal, a browser, or any non-sandbox network.

## Quick-decision matrix

| Situation | Pattern |
| --- | --- |
| Anything, from a Cowork session | **A** (the skill decides B vs C for you) |
| Probe passes + source readable in sandbox | **B** — zero-click, any size |
| Probe fails, R2 host blocked, or file not in the sandbox | **C** — clickable script / local CLI |
| Any size at all | Never base64 — \`cdn_upload_file\` rejects |

# Quick reference — "I want to X" → call Y

| What I want to do | Tool to call |
| --- | --- |
| Upload bytes (any size) | the \`cdn-file-upload\` skill — or, by hand, \`cdn_signed_upload_url\` → (PUT bytes) → \`cdn_finalize_upload\` |
| Update existing without breaking links | \`cdn_replace_file\` |
| Upload a video > 100MB | same as above — size doesn't change the path |
| List everything globally | \`cdn_list_files\` (no args) |
| List files in one folder | \`cdn_list_files({project})\` |
| List all folders | \`cdn_list_projects\` |
| Get one file's metadata | \`cdn_get_file\` |
| Get global totals + per-project breakdown | \`cdn_get_stats\` |
| Get one folder's totals | \`cdn_get_stats({project})\` |
| Pre-create an empty folder | \`cdn_create_project\` |
| Delete a file | \`cdn_delete_file\` |

# What's not available yet

- **\`cdn_rename_file\`** — currently a stub. Workaround: re-upload under the new name (skill, or \`cdn_signed_upload_url\` → PUT → \`cdn_finalize_upload\`), then \`cdn_delete_file\` on the old. Note this changes the public URL.
- **\`cdn_set_cache_headers\`** — currently a stub. The default \`Cache-Control: public, max-age=60\` is global and tuned for fast replace visibility. To change globally, edit \`DEFAULT_CACHE_CONTROL\` in \`src/mcp/util.ts\` and redeploy.
- **Admin UI / D1 explorer** — parked. Use the \`cdn_list_*\` and \`cdn_get_*\` tools, or the Cloudflare R2 dashboard for raw browsing.

# Validation rules (avoid errors)

## Project names

- Allowed characters: \`[a-zA-Z0-9_-]\` (letters, digits, underscore, dash).
- Length: 1–64 characters.
- Examples that work: \`blog\`, \`client-deliverables\`, \`irondad_v2\`.
- Examples that fail: \`client deliverables\` (space), \`proj.name\` (dot), empty string, 100-char string.

## Filenames within a project

- Cannot start with \`/\` or \`.\`.
- Cannot contain \`..\` segments (path traversal).
- Cannot contain NUL bytes or backslashes.
- Internal slashes ARE allowed (sub-paths).
- Length cap: 256 characters.
- Examples that work: \`hero.png\`, \`q2/report.pdf\`, \`raw/demo-final.mp4\`.
- Examples that fail: \`/leading-slash.png\`, \`../escape.png\`, \`back\\\\slash.png\`.

# Tips

- **Stable links matter.** Once you embed a CDN URL in a blog post, email, or document, changing it breaks references. \`cdn_replace_file\` is the right tool for keeping URLs while updating bytes.
- **Cache window is 60 seconds.** After replace, fresh bytes serve at the public URL within 60s. For instant verification, append a cache-buster query param like \`?v=2\` or \`?bust=<timestamp>\`.
- **Project naming.** Use lowercase short names. They appear in URLs, so \`blog\` is friendlier than \`BlogContent_2026\`.
- **Filename versioning is optional.** You can either bake versions into filenames (\`post-v2.png\`) or rely on \`cdn_replace_file\` + cache-busting. The CDN's \`version\` field tracks replace count regardless.
- **Audit storage with \`cdn_get_stats\`.** R2's free tier is 10GB. Watch the trend.
- **Free tier is real.** For personal usage you'll likely never pay anything. R2: 10GB storage + 1M Class A operations/month free. D1: 5GB + 25M row reads/day free. Worker: 100K requests/day free.

# Where this came from

Built phase-by-phase using a head-session/builder-session orchestration pattern (head session plans + writes prompts; isolated builder sessions ship code). All decisions, tests, and tradeoffs documented in:

- CDN w MCP — Build Plan (architecture, tool surface, head-session pre-flight rules, deferred trade-offs, task tracker).
- CDN w MCP — Test Reports (per-phase test runs and trend table).
- Source on GitHub: https://github.com/code22d/cdn-mcp (private).
`;
